"""Add image filename to travel posts

Revision ID: 3de32a450ac7
Revises: 
Create Date: 2026-08-12 21:44:39.227578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de32a450ac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_post', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
